# Generated by Django 3.2.5 on 2021-08-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='имя продавца')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='название товара')),
                ('item_description', models.TextField(verbose_name='описание товара')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена товара')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.IntegerField(default=1, verbose_name='количество товара')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='окончательная цена товара')),
                ('purchase_date', models.DateTimeField(auto_now=True, verbose_name='дата покупки')),
                ('sale_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.employee')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='новая цена')),
                ('price_change_time', models.DateTimeField(auto_now=True, verbose_name='время изменения цены')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.item')),
            ],
        ),
    ]
